version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'traffic'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
      interval: 5s
      retries: 3
      start_period: 10s

  web:
    image: jeanvega/infracciones:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for the MySQL service
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=traffic
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=admin

volumes:
  mysql_data:
