# Generated by Django 4.2.11 on 2024-04-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='user',
            new_name='oficial',
        ),
    ]
